nls-oskari/pti-frontend

bundles/paikkatietoikkuna/terrain-profile/instance.js
bundles/paikkatietoikkuna/terrain-profile/resources/css/terrainprofile.css
bundles/paikkatietoikkuna/terrain-profile/resources/locale/en.js
bundles/paikkatietoikkuna/terrain-profile/resources/locale/fi.js
bundles/paikkatietoikkuna/terrain-profile/resources/locale/sv.js
bundles/paikkatietoikkuna/terrain-profile/view/TerrainFlyout.js

show error text and stop spinner on error .

Terrain-profile show error

---

packages/paikkatietoikkuna/bundle/mapmodule/bundle.js

3D view has copy of mapmodule bundle.js

Add missing file

---

bundles/paikkatietoikkuna/terrain-profile/instance.js

Close terrain profile only when newly selected tool is "sticky".

Toolbar button logic

---

bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/en.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/sv.js
bundles/paikkatietoikkuna/coordinatetransformation/service/TransformationService.js

Requires https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/83/files
Fixes an issue where long running coordinate transformation job timed out.

Use long polling to receive result from transformation

---

applications/paikkatietoikkuna.fi/full-map/minifierAppSetup.json
applications/paikkatietoikkuna.fi/full-map_experimental/minifierAppSetup.json

Remove routesearch bundles from minifierAppSetups
Relates to https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/84

Remove route search

---

applications/paikkatietoikkuna.fi/full-map/main.js
applications/paikkatietoikkuna.fi/full-map_experimental/main.js
applications/paikkatietoikkuna.fi/published-map_ol3/main.js
bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Include wfs plugin bundles (mvt & vector)
Fix olcs styles missing

Missing wfs plugin bundles and olcs.css

---

packages/paikkatietoikkuna/bundle/mapmodule/bundle.js

Include missing requests to olcs mapmodule

Add missing requests

---

bundles/paikkatietoikkuna/coordinatetransformation/instance.js

instance.conf was overridden in class_system when app setup config was used.

Fix starting bundle with app setup config

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/en.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/sv.js

Used lang-overrides to add user guide tags for coordinate transformation bundle

Added coordinate transformation user guide

---

packages/paikkatietoikkuna/bundle/mapmodule/bundle.js
packages/paikkatietoikkuna/bundle/terrain-profile/bundle.js

Update package bundle.js to use libraries under oskari-frontend

Update library refs to packages

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js
bundles/paikkatietoikkuna/mapmodule/plugin/LayersPlugin.olcs.js

After changes in oskariorg/oskari-frontend#815

Update imports to changes in core

---

applications/paikkatietoikkuna.fi/full-map/main.js

Lazy load requested implementation of the layer list

Use React layerlist

---

applications/paikkatietoikkuna.fi/full-map/main.js

Fixed loader calls

---

applications/paikkatietoikkuna.fi/full-map/main.js
applications/paikkatietoikkuna.fi/full-map_experimental/main.js
applications/paikkatietoikkuna.fi/published-map_ol3/main.js
bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Update application wfs packages.
Set 3D support on in olcs mapmodule.
Requires https://github.com/oskariorg/oskari-frontend/pull/838

Refactored vector wfs impl

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js
bundles/paikkatietoikkuna/mapmodule/resources/scss/attribution.cs.scss

Display Ion credit when Ion terrain assets are being used.

Show Ion credit when Ion terrain asset is used

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Enables WFS feature click on 3D view.
Contrains commits from https://github.com/nls-oskari/pti-frontend/pull/37
Requires https://github.com/oskariorg/oskari-frontend/pull/911

Wfs click olcs mapmodule

---

bundles/paikkatietoikkuna/dimension-change/instance.js
bundles/paikkatietoikkuna/dimension-change/request/DimensionChangeRequest.js
bundles/paikkatietoikkuna/dimension-change/resources/locale/en.js
bundles/paikkatietoikkuna/dimension-change/resources/locale/fi.js
bundles/paikkatietoikkuna/dimension-change/resources/locale/sv.js
bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js
bundles/paikkatietoikkuna/mapmodule/plugin/controls/ToolSelectionHandler.js
bundles/paikkatietoikkuna/tiles3d/domain/Tiles3DLayer.js
bundles/paikkatietoikkuna/tiles3d/plugin/Tiles3DLayerPlugin.js
packages/paikkatietoikkuna/bundle/dimension-change/bundle.js

PR for demonstrating dimension changing

Dimension change map state check

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Fixes an issue where building was visible even when the view was blocked by a hill.

Fix 3D features rendering depth check

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Fix position picking in curved 3D view. Taking the terrain into account.

Refactor map events for 3D

---

applications/paikkatietoikkuna.fi/full-map-3D/main.js
applications/paikkatietoikkuna.fi/full-map/main.js
package.json
theme.less

Import theme from oskari-frontend

Inherit theme

---

bundles/paikkatietoikkuna/coordinatetransformation/view/FileHandler.js

Coordtrans fix line endings

---

applications/paikkatietoikkuna.fi/full-map-3D/main.js
applications/paikkatietoikkuna.fi/full-map/main.js
applications/paikkatietoikkuna.fi/published-map-3D/main.js
applications/paikkatietoikkuna.fi/published-map_ol3/main.js
package.json

Removed mapwfs2 imports.
Requires oskariorg/oskari-frontend#956

Remove deprecated mapwfs2 package imports

---

package.json

Move away from symlinked dependencies.
Symlinking is still available in dev-mode.
* dev-mode:enable
* build:dev
* start:dev

Use GitHub dependencies

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Fix scope bug

---

applications/embedded-3D/main.js
applications/embedded/main.js

Fixes an error that occurred on some publications.

Load divmanazer eagerly

---

applications/embedded-3D/main.js
applications/geoportal-3D/main.js

After: https://github.com/oskariorg/oskari-frontend/pull/1169

Rename shadowplugin to time-control-3d

---

applications/embedded-3D/css/overwritten.css
applications/embedded/css/overwritten.css
applications/geoportal-3D/css/overwritten.css
applications/geoportal/css/overwritten.css

Increase specificity to override tavble styling

increase specifity to override styling

---

bundles/paikkatietoikkuna/telemetry/instance.js

Also requires config change in oskari-ext.properties

Change piwik -> matomo

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/en.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/sv.js

In oskariorg/oskari-frontend#1350

To preserve descriptions since defaults have changed in oskari-frontend

---

bundles/paikkatietoikkuna/layerstatus/instance.js

And exclude runtime vector layers like statistical maps region sets.

Combine known internal layers from error tracking

---

applications/geoportal-3D/main.js
applications/geoportal/main.js

Add userstyle bundle to geoportal and geoportal 3D main.js

Userstyle add bundle

---

bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateSystemSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/en.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/sv.js

Show info popup if user selects N43 height system.

CoordTrans n43 info popup

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/en.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/sv.js

Change search description

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js

Changes finnish search description.

Fix finnish search description

---

.github/workflows/run_tests.yml

Related: https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/172

Cancel CI build when a new one would be triggered while its running

---

bundles/paikkatietoikkuna/coordinatetransformation/Flyout.js
bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateSystemSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateTable.js
bundles/paikkatietoikkuna/coordinatetransformation/components/SourceSelect.js
bundles/paikkatietoikkuna/coordinatetransformation/components/select.js
bundles/paikkatietoikkuna/coordinatetransformation/instance.js
bundles/paikkatietoikkuna/coordinatetransformation/service/TransformationService.js
bundles/paikkatietoikkuna/coordinatetransformation/util/CoordinateDataHandler.js
bundles/paikkatietoikkuna/coordinatetransformation/util/helper.js
bundles/paikkatietoikkuna/coordinatetransformation/view/CoordinateMapSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/view/CoordinateSystemInformation.js
bundles/paikkatietoikkuna/coordinatetransformation/view/FileHandler.js
bundles/paikkatietoikkuna/coordinatetransformation/view/mapmarkers.js
bundles/paikkatietoikkuna/coordinatetransformation/view/transformation.js
bundles/paikkatietoikkuna/register/instance.js
bundles/paikkatietoikkuna/routesearch/Flyout.js
bundles/paikkatietoikkuna/routesearch/instance.js
bundles/paikkatietoikkuna/telemetry/instance.js
bundles/paikkatietoikkuna/terrain-profile/instance.js
bundles/paikkatietoikkuna/terrain-profile/view/TerrainFlyout.js
bundles/paikkatietoikkuna/terrain-profile/view/TerrainPopup.js

Changes based on ESLint config changes in oskariorg/oskari-frontend#1765

Eslint fixes

---

applications/geoportal-3D/main.js
applications/geoportal/main.js

Mydata is the new React.js based replacement for personaldata with some events/requests replaced with service API for registering more tabs from functionalities.

Replace personaldata with mydata bundle

---

applications/embedded/main.js

Add metadataflyout bundle.

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/en.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/sv.js

https://github.com/oskariorg/oskari-frontend/pull/2138
https://github.com/oskariorg/oskari-frontend/blob/develop/bundles/mapping/mapmodule/resources/locale/en.js#L123-L128

lang-overrides remove unsupported dimension

---

bundles/paikkatietoikkuna/inspire/Flyout.js
bundles/paikkatietoikkuna/inspire/resources/locale/en.js
bundles/paikkatietoikkuna/inspire/resources/locale/sv.js

Social media links removed from english on purpose as its only using finnish language.
Added max-width so text is more readable on larger screen.

Service info updates

---

applications/geoportal/main.js

and make metadata bundles lazy loaded as they are not started on mobile mode.

Change permission bundle and lazy load more bundles

---

applications/geoportal-3D/index.js
applications/geoportal/index.js
bundles/paikkatietoikkuna/mobileuserguide/instance.js
bundles/paikkatietoikkuna/mobileuserguide/resources/locale/en.js
bundles/paikkatietoikkuna/mobileuserguide/resources/locale/fi.js
bundles/paikkatietoikkuna/mobileuserguide/resources/locale/sv.js
package.json

Release as 1.26.1 PTI with Oskari 2.12.0

Add "Show all functionalities" link to mobile view

---

applications/embedded-3D/main.js
applications/embedded/main.js
applications/geoportal-3D/main.js
applications/geoportal/main.js

Related to https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/217

Replace metadata search and feature data with new impls

---

applications/geoportal/main.js

So we can start testing it right away

Link new statsgrid instead of old one

---

applications/embedded/main.js

lazyload layerswipe in embedded maps

include layerswipe bundle in embedded map

---

applications/geoportal/index.js

remove frontend hardcoding and add to db instead (related server pr:  https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/226)

remove layeranalytics bundle hardcoding

---

applications/embedded/main.js
applications/geoportal-3D/main.js
applications/geoportal/main.js

use new metadata flyout implementation:
https://github.com/oskariorg/oskari-frontend/pull/2687

Metadata flyout new impl

---

applications/embedded-3D/main.js
applications/embedded/main.js
applications/geoportal-3D/main.js
applications/geoportal/main.js

Packages migration due to https://github.com/oskariorg/oskari-frontend/pull/2798

Migrate loader and packages -> bundles

---

applications/embedded-3D/main.js
applications/geoportal-3D/main.js
applications/geoportal/main.js

https://github.com/oskariorg/oskari-frontend/pull/2803

Migrate more packages

---

bundles/paikkatietoikkuna/lang-overrides/resources/locale/en.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/fi.js
bundles/paikkatietoikkuna/lang-overrides/resources/locale/sv.js
package.json

Skipping the KOMU changes for this one.

2.1.0 with Oskari 3.1.0
