bundles/paikkatietoikkuna/coordinatetransformation/Flyout.js
bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateSystemSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/components/SourceSelect.js
bundles/paikkatietoikkuna/coordinatetransformation/instance.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/css/coordinatetransformation.css
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/en.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/sv.js
bundles/paikkatietoikkuna/coordinatetransformation/util/helper.js
bundles/paikkatietoikkuna/coordinatetransformation/view/FileHandler.js
bundles/paikkatietoikkuna/coordinatetransformation/view/transformation.js

Bug fixes:
- start spinner only when request is sent
- set flyout container max height and top on attach (on start plugin can't calculate content height)
- update input table and input coords on system selection change (fix issue 2d <-> 3d)
- replace epsg-code to transform if hidden epsg is used (from epsg search)
Add info popups also to source selections because other info icons opens popup.
Update localization files

CoordTrans bug fixes and localization update

---

applications/paikkatietoikkuna.fi/full-map/minifierAppSetup.json

Could not add as lazy because WFS is not an independent bundle with entry in startup sequence.

WFS MVT implementation

---

bundles/paikkatietoikkuna/coordinatetransformation/service/TransformationService.js

Fixes an issue where export file's name was not the one user had asked for.

Fix coordinate transformation file naming issue

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Turn `highDynamicRange` off to get bright layer imagery.

Make 3D bright again

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

Since `scene.globe.depthTestAgainstTerrain` was enabled, vector features "sank" in the terrain. 
This fixes that problem at some level. Works better on quantized-mesh terrain.

Clamp vector features to ease sinking problem

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

We should add logic to enable depth check when 3D tiles are being used.
Disabling check for now, because clamping vector features to ground isn't working good enough.

Disable depth check

---

bundles/paikkatietoikkuna/mapmodule/mapmodule.olcs.js

This should fix the call when centerMap is called directly.

Fix zoomToExtent on cesium maps

---

theme.less

Required after https://github.com/oskariorg/oskari-frontend/pull/999.
Update path to ant-theme.less
Comment out yellow primary color overwrite to use blue theme.
Leaving the comment there to implicate overwriting possibility.

Update pti theming

---

applications/embedded-3D/main.js
applications/geoportal-3D/main.js

Reverts nls-oskari/pti-frontend#63 as the bundles are not in oskari-frontend yet

Revert "Add new camera-controls-3d bundle to 3D applications"

---

bundles/paikkatietoikkuna/terrain-profile/view/TerrainFlyout.js

Intl.NumberFormat uses &nbsp as space grouping char. Replace it by space for map marker.

Terrain-profile &nbsp

---

bundles/paikkatietoikkuna/coordinatetransformation/components/SourceSelect.js
bundles/paikkatietoikkuna/coordinatetransformation/view/CoordinateMapSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/view/transformation.js

The radio buttons in coordinate transformation have visually broken after oskari-frontend 1.55.2 release. Suspecting it's because of the jQuery update https://github.com/oskariorg/oskari-frontend/pull/1282 but luckily the fix was easy. The empty spans are used for creating a radio-button'ish component. After 1.55.2 the text contents that previously were after the empty span tag in the DOM is now inside the span tag. This change fixes the DOM so text contents are again after the span and not inside it and makes the radio buttons visually correct.

Fix radio buttons on coordinate transformation UI

---

bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/en.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/sv.js
bundles/paikkatietoikkuna/coordinatetransformation/view/FileHandler.js

Coordinate transformation service has only win and unix options for line endings. https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/pull/145
Remove mac option and update unix option label to: UNIX / Mac
Remove localization because code isn't using it and there's no need for localized labels.

CoordinateTransformation remove MacOS line ending option

---

applications/geoportal/main.js

Use dynamic imports so they are not bundled in if we forget them for prod release. There's no migration to add these to apps yet (until we test if we want to have them) so you will need to run these in browsers dev-console:
```
Oskari.app.playBundle({ bundlename : 'announcements' });
Oskari.app.playBundle({ bundlename : 'admin-announcements' });
```

Add announcements for testing

---

applications/geoportal/index.js
applications/geoportal/main.js
bundles/paikkatietoikkuna/layerstatus/bundle.js
bundles/paikkatietoikkuna/layerstatus/instance.js

Send info about layer usage and errors when loading layers when the user exits the page. The purpose is to determine which layers should be marked unstable or in an error status for the end-users.

Track layer error events

---

applications/geoportal/index.js
util/PTIOrtophotoTimeseriesGFIformatter.js

Uses oskariorg/oskari-frontend#1481 to customize GFI response formatting for historical ortophotos.
Configured with admin-layereditor by adding something like this to layer attributes field:
```
{
"PTI_GFI_formatter": "latestPhotoYear",
"PTI_GFI_property": "kuvausvuosi",
"PTI_GFI_label": {
"fi": "Vuosi",
"en": "Year"
}
}
```

Add custom formatter for PTI historical ortophotos

---

applications/geoportal-3D/main.js

- Always bundle `layerlist` as it's the new layer listing UI.
- Never bundle `layerselection2` or `layerselector2` as they are the old layer listings.
- Remove `postprocessor` and `routingService` as they are not used in 3d geoportal.
- Remove `admin-layerselector` as it is the deprecated admin UI that was just removed for Oskari 2.4.

Remove bundles that are no longer used in 3d

---

bundles/paikkatietoikkuna/inspire/Flyout.js

We use localization of bundle instance so local localization is unnecessary.

Remove unnecessary localization variable

---

applications/geoportal-3D/main.js
applications/geoportal/main.js

Always package komu and layerswipe for 2d as they are always used there. Remove komu from 3d as it's not used there.

Tune app package

---

bundles/paikkatietoikkuna/coordinatetransformation/resources/css/coordinatetransformation.css

Related oskariorg/oskari-frontend#1629 / AntD CSS reset with box-sizing: border-box for all components.

Visual fix caused by AntD reset css/box-sizing

---

applications/embedded/main.js

To get rid of a warning when the plugin is not part of the embedded map.

Check if plugin exists before attaching formatter

---

applications/embedded-3D/css/overwritten.css
applications/embedded/css/overwritten.css
applications/geoportal-3D/css/overwritten.css
applications/geoportal/css/overwritten.css

These are not used either `mml-map #wrapper`. Logo is configured on server.

Remove unused CSS

---

package.json

Add support to do `npm run generate-bom` that creates `frontend-bom.json` for further analysis of dependencies.

Add script to generate bom

---

applications/embedded-3D/main.js
applications/embedded/main.js
applications/geoportal-3D/main.js

Related to https://github.com/nls-oskari/pti-frontend/pull/132 /  https://github.com/nls-oskari/pti-frontend/commit/fb4c441ff1151944eba9e8e813a35636a6677c8a
The statsgrid is always loaded lazily. In geoportal so we can leave it out for mobile users and for embedded maps we can leave it out if the publisher isn't using thematic maps. However all lazy-loaded bundles are written parallel to the app-specific folders under dist:
```
embedded <- app
geoportal <- app
resources
...
vendors~chunk_statsgrid  <- lazy loaded bundle used by both apps
```
What happens when embedded and geoportal uses a bundle with the _same id_ but _different source folder_ AND the lazy-loaded bundles _are shared_? Probably chaos ensues...

Switch to new statsgrid in all apps

---

util/PTIOrtophotoTimeseriesGFIformatter.js

Show `-` insted of `-Infinity` if no features/years in GFI response

Ortho GFI no values fix

---

bundles/paikkatietoikkuna/coordinatetransformation/service/TransformationService.js

Encode export settings for A2F transform because Tomcat doesn't like JSON chars in query params.
First tried to use FormData like F2F transformation but backend parses input coords (table/array) from input stream (also for A2A transformation)  so it would require more changes that I thought. As frontend uses jQuery it will be refactored so made only quick fix for now.

CoordTrans encode export settings

---

package.json

#143 added ' around the appdef env-parameter value which breaks it for Windows env. Seems they are not needed atleast on WSL env so removing them.

Fix start:dev for windows env

---

bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/view/transformation.js

That was caused by `<br>` being passed to React instead of `<br />`.

Fix SyntaxError: UNCLOSED_TAG error

---

applications/geoportal-3D/main.js
applications/geoportal/main.js

The `admin-layerrights` was removed in 3.0

Switch admin-layerrights -> admin-permissions in 3d

---

bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateSystemSelection.js
bundles/paikkatietoikkuna/coordinatetransformation/components/CoordinateTable.js
bundles/paikkatietoikkuna/coordinatetransformation/components/SourceSelect.js
bundles/paikkatietoikkuna/coordinatetransformation/view/FileHandler.js
bundles/paikkatietoikkuna/coordinatetransformation/view/transformation.js

refactor lodash template => function + template string literals => using it from code stays as is.
Used editors replace and had only quick check that everything looked same. For some templates used `obj.` (too lazy to check and copy-paste all variable names)
EDIT: for some reason eslint requires no indent after ? and : => disabled rule (I think its easier to read).

CoordTrans remove lodash

---

bundles/paikkatietoikkuna/coordinatetransformation/components/FilePreview.jsx
bundles/paikkatietoikkuna/coordinatetransformation/handler/FileParser.js
bundles/paikkatietoikkuna/coordinatetransformation/handler/ViewHandler.js

Allow file import to use prefix column setting and show first lines of raw input data to make it easier for user to select the settings.

KOMU: Fix file import prefix column setting and improve preview

---

bundles/paikkatietoikkuna/coordinatetransformation/components/SrsSelect.jsx
bundles/paikkatietoikkuna/coordinatetransformation/constants.js
bundles/paikkatietoikkuna/coordinatetransformation/helper.js
bundles/paikkatietoikkuna/coordinatetransformation/view/FlyoutContent.jsx

- update bounds (copied from epsg.io). EUREF-FIN datum is limited to Finland
- swap coordinates for bbox check if needed
- use replaced for search index (user founds new/correct srs with deprecated epsg code)
- add ETRS89 datum as some srs uses it (not EUREF-FIN). Before datum change/update (national srs)  all used same so it didn't rmatter.

Komu bounds update

---

bundles/paikkatietoikkuna/coordinatetransformation/components/FileSettings.jsx
bundles/paikkatietoikkuna/coordinatetransformation/handler/FileParser.js
bundles/paikkatietoikkuna/coordinatetransformation/handler/FileWriter.js
bundles/paikkatietoikkuna/coordinatetransformation/handler/ViewHandler.js
bundles/paikkatietoikkuna/coordinatetransformation/helper.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/en.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/fi.js
bundles/paikkatietoikkuna/coordinatetransformation/resources/locale/sv.js

File settings:
- use mid index for delimeter detection (if first line is header, white spaces caused wrong delimeter detection)
- detect prefixColCount
- detect EPSG code from header lines (loops 4 or 5 digits numbers)
- change detect header lines count to use at least 2 number cells (not all) to detect first data line (prefix or line endings might be non numeric)
- use default values from import file (user may want to use same format/syntax for exported file)
- handle prefixColCount in jsx
Fixes:
- parse result coordinates to float (for file export)
- use `info` as tooltip instead of title (file settings popup)
- parse file always with dimension 3 as srs and/or height might not be selected before import
Add debug transform:
`Oskari.log('CoordTransHandler').enableDebug(true)` …

Komu file settings
